# Generated by Django 4.2.7 on 2023-11-22 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0008_alter_activity_table_activitycostelement'),
        ('process', '0003_directservicecostobject_cant_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityCostObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenance.activity')),
                ('cost_object_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='process.costobject')),
            ],
        ),
    ]
