# Generated by Django 4.2.7 on 2023-11-23 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0004_activitycostobject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Costing',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.IntegerField(blank=True, null=True)),
                ('expenses', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('profit_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sales_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('igv', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('selling_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_user', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('updated_user', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'process_costings',
            },
        ),
        migrations.RenameField(
            model_name='costobject',
            old_name='state',
            new_name='quantity',
        ),
        migrations.RemoveField(
            model_name='costobject',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='costobject',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='costobject',
            name='created_user',
        ),
        migrations.RemoveField(
            model_name='costobject',
            name='expenses',
        ),
        migrations.RemoveField(
            model_name='costobject',
            name='igv',
        ),
        migrations.RemoveField(
            model_name='costobject',
            name='profit_percentage',
        ),
        migrations.RemoveField(
            model_name='costobject',
            name='sales_value',
        ),
        migrations.RemoveField(
            model_name='costobject',
            name='selling_price',
        ),
        migrations.RemoveField(
            model_name='costobject',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='costobject',
            name='updated_user',
        ),
        migrations.AddField(
            model_name='costobject',
            name='costing_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='process.costing'),
            preserve_default=False,
        ),
    ]
