# Generated by Django 4.2.7 on 2023-11-23 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0006_rename_cant_directlaborcostobject_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='costobject',
            name='code',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='costobject',
            name='costing_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='process.costing'),
        ),
    ]
