# Generated by Django 4.2.7 on 2023-11-17 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_alter_inductor_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='activitycenter',
            table='maintenance_activity_centers',
        ),
    ]
