# Generated by Django 4.2.7 on 2023-11-17 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0003_alter_activitycenter_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inductor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='inductor',
            name='created_user',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='inductor',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='inductor',
            name='updated_user',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
