# Generated by Django 4.2.7 on 2023-11-21 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0004_alter_inductor_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostElement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_of_measure', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_user', models.CharField(max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_user', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'maintenance_cost_elements',
            },
        ),
    ]
