# Generated by Django 4.2.7 on 2023-11-21 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0005_costelement'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectLabor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cant', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('cost_per_hour', models.DecimalField(decimal_places=2, max_digits=10)),
                ('state', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_user', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('updated_user', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'maintenance_direct_labors',
            },
        ),
        migrations.CreateModel(
            name='DirectRawMaterial',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('cod', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('state', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_user', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('updated_user', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'maintenance_direct_raw_materials',
            },
        ),
        migrations.CreateModel(
            name='DirectService',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('state', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_user', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('updated_user', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'maintenance_direct_services',
            },
        ),
        migrations.AlterField(
            model_name='activitycenter',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='activitycenter',
            name='created_user',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='activitycenter',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='activitycenter',
            name='updated_user',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='costelement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='costelement',
            name='created_user',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='costelement',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='costelement',
            name='updated_user',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
